#!/usr/bin/env bash

set -e

if [[ -f ".git/hooks/.dirty" ]]; then
    git_rev=$(git rev-parse HEAD)
    rm .git/hooks/.dirty
    echo "${git_rev}" > .git/hooks/hooks-revision
    echo -e "\e[32;1mUpdated git hooks revision to \e[33;1m${git_rev}\e[0m"
fi