#!/usr/bin/env bash

set -e

hooks_diff="$(git diff HEAD -- tools/git-hooks)"
if [[ -n "${hooks_diff}" ]]; then
    echo -e "\e[32;1mDetected update in tools/hooks, marking dirty and installing new hooks\e[0m"
    rm .git/hooks/* # TODO: This could fail on Windows since we are in the pre-commit hook, somebody confirm this
    touch .git/hooks/.dirty
    cp tools/git-hooks/* .git/hooks
fi