//! Various utilities related to Nova's settings
//!
//! Nova itself will take in a struct of settings. These settings should be generated by the application using Nova,
//! possibly by reading from an on-disk configuration file or asking the end user for settings. The settings are then
//! used throughout Nova for various purposes. While most of these settings will be pretty technical and only useful to
//! the application developer, a few of these, such as the API to use, will likely be more interesting for the end user

mod settings_enums;
mod settings_structs;
mod settings_traits;

// Re-exports
pub use settings_enums::*;
pub use settings_structs::*;
pub use settings_traits::*;
